---

kind: pipeline
name: node8

steps:
- name: build
  image: node:8
  commands:
  - node -v
  - yarn -v
  - uname -r
  - yarn install
  - export PATH=$PATH:./node_modules/.bin/
  - lerna bootstrap --npm-client yarn
  - lerna run build --npm-client yarn --ignore "@openprofiling/inspector-trace-events"
  - lerna run test --npm-client yarn --ignore "@openprofiling/inspector-trace-events"
  environment:
    NODE_ENV: test
    S3_HOST: minio
  when:
    event:
    - push
services:
- name: minio
  image: minio/minio
  environment:
    MINIO_ACCESS_KEY: accessKey
    MINIO_SECRET_KEY: secretKey
  entrypoint: [ 'minio', 'server', '/data' ]

---

kind: pipeline
name: node10

steps:
- name: build
  image: node:10
  commands:
  - node -v
  - yarn -v
  - uname -r
  - yarn install
  - export PATH=$PATH:./node_modules/.bin/
  - lerna bootstrap --npm-client yarn
  - lerna run build --npm-client yarn
  - lerna run ci --npm-client yarn
  environment:
    NODE_ENV: test
    S3_HOST: minio
    CODECOV_TOKEN:
      from_secret: coverage_token
  when:
    event:
    - push
services:
- name: minio
  image: minio/minio
  environment:
    MINIO_ACCESS_KEY: accessKey
    MINIO_SECRET_KEY: secretKey
  entrypoint: [ 'minio', 'server', '/data' ]

---

kind: pipeline
name: node11

steps:
- name: build
  image: node:11
  commands:
  - node -v
  - yarn -v
  - uname -r
  - yarn install
  - export PATH=$PATH:./node_modules/.bin/
  - lerna bootstrap --npm-client yarn
  - lerna run build --npm-client yarn --ignore "@openprofiling/heapsnapshot"
  - lerna run test --npm-client yarn --ignore "@openprofiling/heapsnapshot"
  environment:
    NODE_ENV: test
    S3_HOST: minio
  when:
    event:
    - push
services:
- name: minio
  image: minio/minio
  environment:
    MINIO_ACCESS_KEY: accessKey
    MINIO_SECRET_KEY: secretKey
  entrypoint: [ 'minio', 'server', '/data' ]

---

kind: pipeline
name: node12

steps:
- name: build
  image: node:12
  commands:
  - node -v
  - yarn -v
  - uname -r
  - yarn install
  - export PATH=$PATH:./node_modules/.bin/
  - lerna bootstrap --npm-client yarn
  - lerna run build --npm-client yarn --ignore "@openprofiling/inspector-heapsnapshot"
  - lerna run test --npm-client yarn --ignore "@openprofiling/inspector-heapsnapshot"
  environment:
    NODE_ENV: test
    S3_HOST: minio
  when:
    event:
    - push
services:
- name: minio
  image: minio/minio
  environment:
    MINIO_ACCESS_KEY: accessKey
    MINIO_SECRET_KEY: secretKey
  entrypoint: [ 'minio', 'server', '/data' ]

---

kind: pipeline
name: linter

steps:
- name: build
  image: node:10
  commands:
  - node -v
  - yarn -v
  - uname -r
  - yarn install
  - export PATH=$PATH:./node_modules/.bin/
  - lerna bootstrap --npm-client yarn
  - lerna run lint --npm-client yarn
  when:
    event:
    - push
